### ISSUE TITLE
Custom `rust-toolchain.toml` is being ignored

### ISSUE THREAD

**Issue by ChristianIvicevic** [vercel-community/rust#132]
Earlier today I realized that my attached `rust-toolchain.toml` is unfortunately ignored. During a deployment the Vercel build logs clearly show `stable-x86_64-unknown-linux-gnu installed - rustc 1.73.0 (cc66ad468 2023-10-03)` instead of the expected nightly. This prevents me from using some convenient features sadly.
```toml
[toolchain]
channel = "nightly-2023-09-21"
```
