### ISSUE TITLE
failed to get `models` as a dependency of package `api v0.1.0 (/vercel/path0)`

### ISSUE THREAD

**Issue by devklick** [vercel-community/rust#172]
Are cargo workspaces supported? If so, I would appreciate some help with a deployment error I'm seeing. 

My workspace has a binary (`api`) and a library (`models`). `api` depends on `models`. The api is what I'm trying to deploy, but it fails with an error in the web console build logs:

>failed to get `models` as a dependency of package `api v0.1.0 (/vercel/path0)`

How would I go about including the models library in with my api deployment?

I notice that the only mention of "workspace" in the readme is for [Experimental API Bundling](https://github.com/vercel-community/rust?tab=readme-ov-file#experimental-api-bundling) - is this the only option when it comes to workspaces?

**api Cargo.toml**
```toml
[package]
name = "api"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "hello"
path = "api/hello.rs"

[dependencies]
models = { path = "../models" }
vercel_runtime = "1.1.4"
```

**api vercel.json**
```json
{
  "$schema": "https://openapi.vercel.sh/vercel.json",
  "outputDirectory": "public",
  
  "functions": {
    "api/**/*.rs": {
      "runtime": "vercel-rust@4.0.7"
    }
  }
}
```

The code works fine when running with `vercel dev`, but I guess the deploy doesnt know about the models lib and falls over because it doesnt get uploaded.
